---
- name: Platform Applications
  hosts: platform
  gather_facts: false
  vars:
    app_cfg: "{{ playbook_dir }}/../platform/{{ inventory_hostname }}.yaml"
    default_app_state: present
  tasks:
    - delegate_to: localhost
      block:
        - name: load component configuration
          include_vars:
            file: "{{ app_cfg }}"
            name: app

        - name: get component state
          set_fact:
            app_state: "{{ app.state|default(default_app_state) }}"

        - name: remove deleted components
          when: app_state == 'absent'
          k8s:
            state: absent
            kind: Namespace
            name: "{{ inventory_hostname }}"
            wait: true

        - name: deploy current components
          when: app_state != 'absent'
          k8s:
            resource_definition: "{{ lookup('template', 'platform/' ~ app.kind ~ '.yaml') }}"
